### ISSUE TITLE
Teams import from .csv file sometimes doesn't import all teams

### ISSUE THREAD

**Issue by alanggreen** [FirstLegoLeagueIL/fllscoring#114]
With the attached .csv file, when dropping into paste box, not all teams are in list of teams to import 
### Paste box
Team Number,Team Name
1606,Pirate Hogs
3007,Batteries
1585,SMS PUMAS 2
1439,Sea Urchins
1587,Sky Surfing Geeks

### Teams to import box
1585 | SMS PUMAS 2
1439 | Sea Urchins
1587 | Sky Surfing Geeks

Pressing Ok imports the 3 teams only.
[short team list with header.zip](https://github.com/FirstLegoLeagueIL/fllscoring/files/1503228/short.team.list.with.header.zip)

**Comment by alanggreen** [comment]
Need to test with this file too. 
[schedule_ranking.zip](https://github.com/FirstLegoLeagueIL/fllscoring/files/1503757/schedule_ranking.zip)
It has teams with non-ascii characters in their names

**Comment by ThinkRedstone** [comment]
It doesn't import all teams because the default header length for csv files is 3, matching up with the the other examples you sent (including the one in your more recent comment). This CSV file seems to be of a different format, with only one line of header- and since PR #119 fixes the header option, and the team import dialog can't divine the header length on its own, I would say this issue is more with how the team import dialog is used than the it in itself.

**Comment by idanstark42** [comment]
If it doesn't fit the program, it should just use one line header, no?

**Comment by idanstark42** [comment]
Fits the format*

**Comment by alanggreen** [comment]
The two options we need are:
1. Drag in a .csv file like the ones I attached. Has a header of 3 lines,
and the 3rd line says how many teams there are. Teams start in 4th line.
Idan's regex could be used to identify files like these. Import team number
and team name.
2. Drag in or paste a .csv file. File might have a single line header. No
automatic detection of header. User must select the checkbox to ignore the
1st line. Import 1st and 2nd columns for team number and team name. Stop
importing when either the cell in col 1 or col 2 is blank.
